### ISSUE TITLE
A couple of fixes.

### ISSUE THREAD

**Issue by bropines** [CheshireCC/faster-whisper-GUI#46]
I'm honestly not much of a coder, but it took me half an evening to stupidly run it....

### 1. Libraries in `requirements.txt`.
```pip
pyside6-fluent-widgets
faster-whisper==0.10.0
pyAV
ffmpeg-python
pyAudio
nltk
CTranslate2>=3.21.0
joblib==1.2.0
pyside6==6.4.2
webvtt-py
pandas
transformers
pyannote.audio
```
and 
Cuda 12.1
```pip
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```
or Cuda 11.8
```pip
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

### 2. Loglines.
WHY DO I NEED TO OUTPUT THE DOWNLOAD LOGS TO A LOG FILE? 
Why not just parse the state of the boot state? Or just output to a log within the program?

### 3. Incorrect import of faster-whisper library.
In many pieces of code the module was imported incorrectly (a lot of moments, I won't describe each one).
From
```python
from faster_whisper import  (Segment, Word)
from typing import List
```
to
```python
from faster_whisper.transcribe import  (Segment, Word)
from typing import List
```
### 4. The problem is cublas. 
To be more precise, faster-whisper requires cublas libraries, in Windows they are from the Nvidia Toolkit. 
Here is links [12.3](https://developer.nvidia.com/cuda-downloads) or (preferably her) [11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive)  for Europe, for China I don't know which one.

Edit: You can just install pytorch 11.8 and everything will work fine without them

### 5. I don't understand the translation system. 
I haven't figured out how to add it, and the English translation is stupidly missing in a couple places.

That's what I found so far, and what I needed to get up and running, I think there are tons more bugs out there....

**Comment by CheshireCC** [comment]
1. I'm very sorry ,I had not written all lib correctly in requirements.txt.That is really my bad
2. In the past, I outout download message in widget of program,but now I do not want to do that again,so I just want some where to save this message.Sadly, fasterWhisper output those message as error but not as stdout.
3. I realese my program with nuitka(without any special reason, just feel cool), if we do not process import function carefully, some problem will come to us，because of the special mechanism of the way that python language process import command.(subobject may not be import correctly after Nuitka working)So, I changed codes of faster-whisper ...
4. In the past, I offer cublas and cudnn with installer program, but now ,our program become more and more bloated， so I do not want to do that ... alas, may be I should think about to update pytorch to higher version ....
5. English translation supported by Qt Linguist. You can google info.
```
pyside6-lupdate <path of code file> -ts <xxx.ts>

then

PySide6-linguist <xxx.ts>
```

in PySide6-Linguist progrom you can change or add English translation.Then release it as `.qm` file, path is
`faster_whisper_gui/resource/_rc/translator/en.qm`,at last, you need to compile `translator.qrc` file, the translation changed will work.

BTW: there is a bug of translation that con not be fixed, I need time to think about  it,this bug is the reason of "stupidly missing English translation", It can not be shown correctly in object of base class of MainWindows, may be, function of sub class converted base-class's.

**Comment by bropines** [comment]
By the way, I'm thinking of closing this issue. In fact, I learned everything I wanted to know about the bugs (albeit known ones). If I find anything, I'll open a new one.
